### ISSUE TITLE
Share attack scripts

### ISSUE THREAD

**Issue by janibashamd** [erev0s/VAmPI#20]
Hi,

I can see doc says this demo app supports multiple attacks but i don't see attack payloads. So can you please share them so i can also test these attacks.

Thanks,
Jani

**Comment by erev0s** [comment]
hey @janibashamd attack payloads are not provided. All the attacks though are pretty straight forward.
Might be an idea to create a postman collection with the usual payloads (sqli, mass assignment etc.)

**Comment by janibashamd** [comment]
Yes for a novice user like me it will be really helpful if you can provide steps of each attack or provide us postman collection for each attack.

**Comment by janibashamd** [comment]
@erev0s atleast tell me about sqli and ReDOS attacks generation steps please.
I am trying these 2 as per docs but seems like attack is not getting generated.

I will really appreciate if you can provide above 2 attacks as it's little critical for me..

**Comment by erev0s** [comment]
Update the postman collection with some examples for some specific attacks.
You can also check the blog post here https://erev0s.com/blog/vampi-vulnerable-api-security-testing/
for more details for the rest of the attacks that does not make sense to put in an example in the collection.
