### ISSUE TITLE
Suggestions for README

### ISSUE THREAD

**Issue by aaronhmiller** [erev0s/VAmPI#3]
Love this project! Thank you.
Opening an issue to use w/ a PR I'm about to submit.

To make it even easier and more powerful to use as a teaching tool, it is handy to run one instance of VAmPI securely (vulnerable=0) and another insecure instance running in parallel on a different port (vulnerable=1). Your use of ENV within the Dockerfile makes this dead simple and adjustments to the README are all that is needed.

Also ran into a conflict w/ port 5000 on Mac OSX, so put in a note about two ways to resolve that.

**Comment by erev0s** [comment]
hi @aaronhmiller, indeed a nice thought of you.
