### ISSUE TITLE
flask-sqlalchemy incompatible version - with solution -

### ISSUE THREAD

**Issue by bipbopbup** [erev0s/VAmPI#32]
Linux version: Ubuntu 22.04.1
Summary: flask-sqlalchemy version when installing requirements.txt is incompatible and raises error shown below:

AttributeError: module 'sqlalchemy' has no attribute '__all__'. Did you mean: '__file__'?

Following updated requirements.txt solves this error:

connexion~=2.7.0
flask~=2.2
flask-sqlalchemy>=3.0.2
jsonschema~=3.2.0
sqlalchemy
swagger-ui-bundle
PyJWT~=1.7.1
markupsafe==2.1.1

**Comment by erev0s** [comment]
thank you @bipbopbup 
I updated the requirements all together
