### ISSUE TITLE
get_users return repr format when vulnerable=0

### ISSUE THREAD

**Issue by Sheryx00** [erev0s/VAmPI#39]
The get_user method in the `models/user_model.py` return the _ _repr_ _ format when `vulnerable=0`.

#### Example
```
$ curl "http://localhost:5000/users/v1/name1"
<User(name=name1, email=mail1@mail.com)>
```

This not happen when the vulnerable environment is True, because in that scenario the response is a formatted string, meanwhile in this one it returns the first user object found:

```
78   else:
79     fin_query = User.query.filter_by(username=username).first()

```

#### Possible solution:

We can take advance of the json class method to return the user data:

```
      else:
          user = User.query.filter_by(username=username).first()
          fin_query = user.json() if user else None
      return fin_query

```
> Note: Calling .json() of a NoneType object could raise an error, so we must check if exists first. 

But the .json() class method encloses the value in single quotes. That's not the standard json syntax we are looking for. A better solution could be like this:

```
      else:
          user = User.query.filter_by(username=username).first()
          fin_query = str(User.json(user)).replace("'",'"') if user else None
      return fin_query
```

#### Result:

```
$ curl "http://localhost:5000/users/v1/name1" # not vuln
{"username": "name1", "email": "mail1@mail.com"}

$ curl "http://localhost:5001/users/v1/name1" # vuln
{"username": "name1", "email": "mail1@mail.com"}
```

**Comment by erev0s** [comment]
hi @Sheryx00 
although it does not make a difference in the execution part it is good that you noticed it so the answers are consistent between the two states (vulnerable/not).
Fixed it by updating the representation of the model directly
https://github.com/erev0s/VAmPI/pull/40
