### ISSUE TITLE
endpoint /users/v1/register behaves differently depending on docker image (dockerhub vs dockerfile) 

### ISSUE THREAD

**Issue by archidote** [erev0s/VAmPI#45]
Hello,

Firstly, thank you for this very pleasant project!

I've encountered an ambiguity multiple times during my tests on the /users/v1/register endpoint. When using the image from Docker Hub, I don't get the same result when attempting to promote myself to admin on the API. Specifically, I am unable to perform this privilege escalation from the container linked to the image on Docker Hub, but only through the one I manually build via the project's Dockerfile.

Here are the data I'm sending to the API:

jsonCopy code

`{
    "username": "test2",
    "password": "test",
    "email": "test2@gmail.com",
    "admin": "True"
}`

I want to mention that I also tested with "admin": true.

Here are my tests in more detail with Postman:

Test using the project's Dockerfile

-   User Creation ![1](https://github.com/erev0s/VAmPI/assets/38756128/56e8becb-78b4-4994-af83-2bd99c52204a)

-   Debug Mode: It's observed that the newly added user is an admin! ![2](https://github.com/erev0s/VAmPI/assets/38756128/ada57a49-e9d8-4cdc-a1be-99a194b61022)

Test using the image stored on Docker Hub

-   User Creation ![3](https://github.com/erev0s/VAmPI/assets/38756128/91ba48fc-db07-4e54-8119-711263065404)

-   Debug Mode: It's observed that the newly added user is not an admin... ![4](https://github.com/erev0s/VAmPI/assets/38756128/ca6f7d05-6c26-460b-a69f-10d6bbd07816)

Is this an issue with the image not being updated on Docker Hub? (Last release: 4 months ago: [Docker Hub Link](https://hub.docker.com/r/erev0s/vampi))

I am available if you need more information.

Best regards,

Archidote

**Comment by erev0s** [comment]
hi @archidote 
the dockerhub image is being pushed automatically.
I cant replicate this behavior you are describing.
One thing that comes to mind is that you may be running it in the non-vulnerable mode. To check that you can issue a request to the baseURL (e.g localhost:5000/) and make sure the returned parameter `vulnerable` is set to `1`

**Comment by archidote** [comment]
Hi, that's what it was, I didn't pay attention when copying the commands in the readme. I probably needed someil. sorry to have opened an issue for that. 
++
