### ISSUE TITLE
Broken specification

### ISSUE THREAD

**Issue by shizzgar** [erev0s/VAmPI#52]
Api is responsing with only one object, not a list. 

https://github.com/erev0s/VAmPI/blob/0a5555de955edc604d4e5c50d70cc7bb10662e96/openapi_specs/openapi3.yml#L230C1-L231C23

**Comment by erev0s** [comment]
Thank you @shizzgar , this has been fixed
https://github.com/erev0s/VAmPI/commit/1449f9b198c783c77dfa09b0b316f9f8df77289a
