### ISSUE TITLE
Unable to create DB or write anything into DB.

### ISSUE THREAD

**Issue by darshandkd** [erev0s/VAmPI#58]
The stake-trace appears as below while trying to perform any write operation.

##################
<li><div class="frame" id="frame-139900047935952">
  <h4>File <cite class="filename">"/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py"</cite>,
      line <em class="line">736</em>,
      in <code class="function">do_execute</code></h4>
  <div class="source library"><pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span>def do_executemany(self, cursor, statement, parameters, context=None):</pre>
<pre class="line before"><span class="ws">        </span>cursor.executemany(statement, parameters)</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span>def do_execute(self, cursor, statement, parameters, context=None):</pre>
<pre class="line current"><span class="ws">        </span>cursor.execute(statement, parameters)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def do_execute_no_params(self, cursor, statement, context=None):</pre>
<pre class="line after"><span class="ws">        </span>cursor.execute(statement)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def is_disconnect(self, e, connection, cursor):</pre></div>
</div>
</ul>
  <blockquote>sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: 
DROP TABLE books]
(Background on this error at: https://sqlalche.me/e/14/e3q8)</blockquote>
</div>

<div class="plain">
  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">
    <p>
      <input type="hidden" name="language" value="pytb">
      This is the Copy/Paste friendly version of the traceback.  <span
      class="pastemessage">You can also paste this traceback into
      a <a href="https://gist.github.com/">gist</a>:
      <input type="submit" value="create paste"></span>
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py&quot;, line 1901, in _execute_context
    cursor, statement, parameters, context
  File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py&quot;, line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.7/site-packages/flask/app.py&quot;, line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File &quot;/usr/local/lib/python3.7/site-packages/flask/app.py&quot;, line 2450, in wsgi_app
    response = self.handle_exception(e)
  File &quot;/usr/local/lib/python3.7/site-packages/flask/app.py&quot;, line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File &quot;/usr/local/lib/python3.7/site-packages/flask/_compat.py&quot;, line 39, in reraise
    raise value
  File &quot;/usr/local/lib/python3.7/site-packages/flask/app.py&quot;, line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File &quot;/usr/local/lib/python3.7/site-packages/flask/app.py&quot;, line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File &quot;/usr/local/lib/python3.7/site-packages/flask/app.py&quot;, line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File &quot;/usr/local/lib/python3.7/site-packages/flask/_compat.py&quot;, line 39, in reraise
    raise value
  File &quot;/usr/local/lib/python3.7/site-packages/flask/app.py&quot;, line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File &quot;/usr/local/lib/python3.7/site-packages/flask/app.py&quot;, line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File &quot;/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py&quot;, line 48, in wrapper
    response = function(request)
  File &quot;/usr/local/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py&quot;, line 144, in wrapper
    response = function(request)
  File &quot;/usr/local/lib/python3.7/site-packages/connexion/decorators/parameter.py&quot;, line 121, in wrapper
    return function(**kwargs)
  File &quot;/vampi/api_views/main.py&quot;, line 7, in populate_db
    db.drop_all()
  File &quot;/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py&quot;, line 1102, in drop_all
    self._execute_for_all_tables(app, bind, 'drop_all')
  File &quot;/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py&quot;, line 1086, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py&quot;, line 4960, in drop_all
    ddl.SchemaDropper, self, checkfirst=checkfirst, tables=tables
  File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py&quot;, line 3228, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py&quot;, line 2211, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py&quot;, line 524, in traverse_single
    return meth(obj, **kw)
  File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py&quot;, line 1029, in visit_metadata
    _ignore_sequences=seq_coll,
  File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py&quot;, line 524, in traverse_single
    return meth(obj, **kw)
  File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py&quot;, line 1102, in visit_table
    self.connection.execute(DropTable(table))
  File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py&quot;, line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py&quot;, line 81, in _execute_on_connection
    self, multiparams, params, execution_options
  File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py&quot;, line 1478, in _execute_ddl
    compiled,
  File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py&quot;, line 1944, in _execute_context
    e, statement, parameters, cursor, context
  File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py&quot;, line 2125, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py&quot;, line 211, in raise_
    raise exception
  File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py&quot;, line 1901, in _execute_context
    cursor, statement, parameters, context
  File &quot;/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py&quot;, line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: 
DROP TABLE books]
(Background on this error at: https://sqlalche.me/e/14/e3q8)</textarea>
##################

**Comment by erev0s** [comment]
hi @darshandkd this is missing details but it seems that you might not have the proper permissions on the .db file.
Feel free to share more information on what you are trying to do. Also you might want to try to run it through docker.

**Comment by botwolf444** [comment]
Hi @erev0s 

Even I received same error. I’ve checked the file permissions, and the .db file has the correct read and write permissions. I’m currently running the application directly on my local machine.

I will tried running the application through Docker as you suggested. Could you provide any specific instructions or configurations needed for Docker if they are not already included in the repository’s documentation?

**Comment by botwolf444** [comment]
Hi @erev0s, thanks for your help. I resolved the issue based on your other issue guidance.

Hi @darshandkd, have you tried sending the **GET /createdb** request? It should return the following response:



```
{
    "message": "Database populated."
}
```

This approach worked for me, so I hope it resolves your issue as well.
